services:
  frontend:
    container_name: frontend-container
    image: shoeb5401/chat-app-frontend:v2
    ports:
      - "5173:80"
    networks:
      - chat-app-NW
    environment:
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
    depends_on:
      - backend
      - db
    restart: always

  backend:
    container_name: backend-container
    image: shoeb5401/chat-app-backend:v3
    ports:
      - "5000:5000"
    networks:
      - chat-app-NW
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - MONGODB_URI=${MONGODB_URI}
    restart: always

  db:
    container_name: mongo-container
    image: mongo:noble
    ports:
      - "27017:27017"
    networks:
      - chat-app-NW
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - chat-app-volume:/data/db
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--username",
          "zsm3084",
          "--password",
          "rootpassword",
          "--eval",
          "db.adminCommand('ping')",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  chat-app-NW:

volumes:
  chat-app-volume:
